### ISSUE TITLE
File doesn't get stored correctly to postgresql

### ISSUE THREAD

**Issue by jolappi** [skipperjs/skipper-postgresql#1]
Lots of files are uploaded and downloaded correctly with this adapter but there is one troublesome binary file that gets shorted to 84 bytes after upload/download.

used postgresql version is 9.4.4.1 and sails version 0.11.2 and skipper-postgresql 0.12.1.

Here is the troublesome file included in dropbox.

https://www.dropbox.com/s/nxllukf4lze0alq/tooshort.bin?dl=0

Thanks,
Jouni Lappi

**Comment by tjwebb** [comment]
It looks like the size is 160 bytes. You're saying that once it's loaded into the database, it's only 84 bytes?

**Comment by jolappi** [comment]
Yes, it gets cut down in size and if you load it from database back to disk it will be only 84 bytes. Some other files does this too and yet some files get stored in database correctly.

**Comment by tjwebb** [comment]
I haven't run into this. Is it only binary file types?

**Comment by jolappi** [comment]
No, the problem is not only with binary files, even jpeg's gets sometimes cut. I think ascii files are the only ones that gets always stored correctly.

**Comment by tjwebb** [comment]
@jolappi solved in 0.13.2
